name: Build & Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          node-version: 18
          registry-url: https://registry.yarnpkg.com/
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: yarn build
      - name: Automated tests
        run: yarn test
